use project4;
select * from fact_bookings;
select * from fact_aggregated_bookings;
select * from dim_date;
select * from dim_hotels;
select * from dim_rooms;
desc dim_date;
alter table dim_date add column date1 date;
update dim_date
set date1=str_to_date(`date`,'%d-%b-%y');
alter table dim_date drop column `date`;
alter table dim_date change column date1 `date` date;
alter table fact_bookings add column booking_date1 date , add column check_in_date1 date , add column checkout_date1 date;
desc fact_bookings;
UPDATE fact_bookings
SET
    booking_date1  = STR_TO_DATE(booking_date, '%d-%m-%Y'),
    check_in_date1 = STR_TO_DATE(check_in_date, '%d-%m-%Y'),
    checkout_date1 = STR_TO_DATE(checkout_date, '%d-%m-%Y');
alter table fact_bookings drop column booking_date , drop column check_in_date , drop column checkout_date;
alter table fact_bookings change column booking_date1 booking_date date , change column check_in_date1 check_in_date date , change column checkout_date1 checkout_date date;
alter table fact_aggregated_bookings add column check_in_date1 date;
update fact_aggregated_bookings 
set check_in_date1 = str_to_date(check_in_date, '%d-%b-%y');
alter table fact_aggregated_bookings drop column check_in_date;
alter table fact_aggregated_bookings change column check_in_date1 check_in_date date;

select * from fact_bookings;
select * from fact_aggregated_bookings;
select * from dim_date;
select * from dim_hotels;
select * from dim_rooms;

#1.TOTAL REVENUE #

SELECT SUM(REVENUE_REALIZED) AS "TOTAL REVENUE" FROM FACT_BOOKINGS;

#2. OCCUPANCY #

SELECT SUM(SUCCESSFUL_BOOKINGS) AS "TOTAL  BOOKINGS" , SUM(CAPACITY) AS " TOTAL CAPACITY" , 
concat((SUM(SUCCESSFUL_BOOKINGS)/SUM(CAPACITY))*100,"%") AS OCCUPANCY FROM FACT_AGGREGATED_BOOKINGS;

#3. BOOKING #

SELECT COUNT(BOOKING_ID) AS "TOTAL BOOKINGS" FROM FACT_BOOKINGS;
SELECT SUM(SUCCESSFUL_BOOKINGS) AS "TOTAL BOOKINGS" FROM FACT_AGGREGATED_BOOKINGS;

#4. TOTAL GUESTS #

SELECT SUM(NO_GUESTS) AS "TOTAL GUESTS COUNT" FROM FACT_BOOKINGS;

#5. BOOKING STATUS DETAILS #

SELECT BOOKING_STATUS , COUNT(BOOKING_ID) AS "BOOKING COUNT" FROM FACT_BOOKINGS
GROUP BY 1;

#6. CANCELLATION % #

SELECT SUM(IF(BOOKING_STATUS = "CANCELLED",1,0)) AS "CANCELLATION COUNT",
CONCAT((SUM(IF(BOOKING_STATUS = "CANCELLED",1,0))/COUNT(BOOKING_ID))*100,"%") AS "CANCELLATION %"  FROM FACT_BOOKINGS;

#7. CHECKED OUT % #

SELECT SUM(IF(BOOKING_STATUS = "CHECKED OUT",1,0)) AS "CHECKED OUT COUNT",
CONCAT((SUM(IF(BOOKING_STATUS = "CHECKED OUT",1,0))/COUNT(BOOKING_ID))*100,"%") AS "CHECKED OUT %"  FROM FACT_BOOKINGS;

#8. NO SHOW % #

SELECT SUM(IF(BOOKING_STATUS = "NO SHOW",1,0)) AS "NO SHOW COUNT",
CONCAT((SUM(IF(BOOKING_STATUS = "NO SHOW",1,0))/COUNT(BOOKING_ID))*100,"%") AS "CHECKED OUT %"  FROM FACT_BOOKINGS;

#9. UTILLIZE CAPACITY #

SELECT SUM(CAPACITY) AS "CAPACITY COUNT" , SUM(SUCCESSFUL_BOOKINGS) AS "BOOKING COUNT" ,
CONCAT((SUM(SUCCESSFUL_BOOKINGS)/SUM(CAPACITY))*100,'%') AS "UTILLIZE CAPACITY" FROM FACT_AGGREGATED_BOOKINGS;

#10. TREND ANALYSIS # : REVENUE AND BOOKING COUNT AS PER WEEK DAY TYPE

SELECT DAY_TYPE , SUM(REVENUE_REALIZED) AS REVENUE , COUNT(BOOKING_ID) AS "BOOKING COUNT"
FROM DIM_DATE INNER JOIN FACT_BOOKINGS
ON DIM_DATE.`DATE` = FACT_BOOKINGS.BOOKING_DATE
GROUP BY 1
ORDER BY 2 DESC;

#11. TREND ANALYSIS # : BOOKING STATUS AS PER WEEK DAY TYPE

SELECT DAY_TYPE , BOOKING_STATUS , COUNT(BOOKING_ID) AS "BOOKING COUNT" 
FROM DIM_DATE INNER JOIN FACT_BOOKINGS
ON DIM_DATE.`DATE` = FACT_BOOKINGS.BOOKING_DATE
GROUP BY 1,2
ORDER BY 3 DESC;

#12. TREND ANALYSIS # : MONTH WISE BOOKING COUNT AND REVENUE

SELECT monthname(`DATE`) AS 'MONTH' , COUNT(BOOKING_ID) AS "BOOKING COUNT" , SUM(REVENUE_REALIZED) AS REVENUE
FROM DIM_DATE INNER JOIN FACT_BOOKINGS
ON DIM_DATE.`DATE` = FACT_BOOKINGS.BOOKING_DATE
group by 1 
ORDER BY 2 DESC;

#13. TREND ANALYSIS # : MONTH WISE BOOKING STATUS AS PER BOOKING COUNT AND REVENUE

SELECT monthname(`DATE`) AS 'MONTH' , BOOKING_STATUS , COUNT(BOOKING_ID) AS "BOOKING COUNT" , SUM(REVENUE_REALIZED) AS REVENUE
FROM DIM_DATE INNER JOIN FACT_BOOKINGS
ON DIM_DATE.`DATE` = FACT_BOOKINGS.BOOKING_DATE
group by 1 ,2
ORDER BY 3 DESC;

#14. TREND ANALYSIS # : HOTEL WISE BOOKING STATUS AS PER BOOKING COUNT AND REVENUE

SELECT PROPERTY_NAME , BOOKING_STATUS , COUNT(BOOKING_ID) AS "BOOKING COUNT" , SUM(REVENUE_REALIZED) AS REVENUE
FROM DIM_HOTELS INNER JOIN FACT_BOOKINGS
ON DIM_HOTELS.PROPERTY_ID = FACT_BOOKINGS.PROPERTY_ID
GROUP BY 1,2
ORDER BY 3 DESC;

#15. TREND ANALYSIS # : HOTEL WISE  BOOKING COUNT AND REVENUE

SELECT PROPERTY_NAME , COUNT(BOOKING_ID) AS "BOOKING COUNT" , SUM(REVENUE_REALIZED) AS REVENUE
FROM DIM_HOTELS INNER JOIN FACT_BOOKINGS
ON DIM_HOTELS.PROPERTY_ID = FACT_BOOKINGS.PROPERTY_ID
GROUP BY 1
ORDER BY 2 DESC;

#16. TREND ANALYSIS # : CITY WISE  BOOKING COUNT AND REVENUE

SELECT CITY , COUNT(BOOKING_ID) AS "BOOKING COUNT" , SUM(REVENUE_REALIZED) AS REVENUE
FROM DIM_HOTELS INNER JOIN FACT_BOOKINGS
ON DIM_HOTELS.PROPERTY_ID = FACT_BOOKINGS.PROPERTY_ID
GROUP BY 1
ORDER BY 2 DESC;

#17. TREND ANALYSIS # : CATEGORY WISE  BOOKING COUNT AND REVENUE

SELECT CATEGORY , COUNT(BOOKING_ID) AS "BOOKING COUNT" , SUM(REVENUE_REALIZED) AS REVENUE
FROM DIM_HOTELS INNER JOIN FACT_BOOKINGS
ON DIM_HOTELS.PROPERTY_ID = FACT_BOOKINGS.PROPERTY_ID
GROUP BY 1
ORDER BY 2 DESC;

#18. TREND ANALYSIS # : BOOKING STATUS AS PER CATEGORY WISE  BOOKING COUNT AND REVENUE

SELECT CATEGORY , BOOKING_STATUS , COUNT(BOOKING_ID) AS "BOOKING COUNT" , SUM(REVENUE_REALIZED) AS REVENUE
FROM DIM_HOTELS INNER JOIN FACT_BOOKINGS
ON DIM_HOTELS.PROPERTY_ID = FACT_BOOKINGS.PROPERTY_ID
GROUP BY 1,2
ORDER BY 3 DESC;

#19. TREND ANALYSIS # : ROOM CLASS WISE  BOOKING COUNT AND REVENUE

SELECT ROOM_CLASS , COUNT(BOOKING_ID) AS "BOOKING COUNT" , SUM(REVENUE_REALIZED) AS REVENUE
FROM DIM_ROOMS INNER JOIN FACT_BOOKINGS
ON DIM_ROOMS.ROOM_ID = FACT_BOOKINGS.ROOM_CATEGORY
GROUP BY 1
ORDER BY 2 DESC;

#20. TREND ANALYSIS # : BOOKING STATUS AS PER ROOM CLASS WISE  BOOKING COUNT AND REVENUE

SELECT ROOM_CLASS , BOOKING_STATUS , COUNT(BOOKING_ID) AS "BOOKING COUNT" , SUM(REVENUE_REALIZED) AS REVENUE
FROM DIM_ROOMS INNER JOIN FACT_BOOKINGS
ON DIM_ROOMS.ROOM_ID = FACT_BOOKINGS.ROOM_CATEGORY
GROUP BY 1,2
ORDER BY 3 DESC;

#21. TREND ANALYSIS # : BOOKING PLATFORM WISE  BOOKING COUNT AND REVENUE

SELECT BOOKING_PLATFORM , SUM(REVENUE_REALIZED) AS REVENUE , COUNT(BOOKING_ID) AS "BOOKING COUNT" 
FROM FACT_BOOKINGS
GROUP BY 1 
ORDER BY 2;

#22. AVERAGE LENGTH OF STAY

SELECT ABS(AVG(DATEDIFF(CHECK_IN_DATE,CHECKOUT_DATE))) AS "AVG_LENGTH OF STAY" FROM FACT_BOOKINGS;

#23. AVERAGE LENGTH OF STAY IN EACH HOTEL

SELECT PROPERTY_NAME , ABS(AVG(DATEDIFF(CHECK_IN_DATE,CHECKOUT_DATE))) AS "AVG_LENGTH OF STAY" 
FROM DIM_HOTELS INNER JOIN FACT_BOOKINGS
ON DIM_HOTELS.PROPERTY_ID = FACT_BOOKINGS.PROPERTY_ID
GROUP BY 1 
ORDER BY 2;

#24. AVERAGE RATING

SELECT AVG(RATINGS_GIVEN) AS RATINGS FROM FACT_BOOKINGS;

#25. AVERAGE RATINGS OF EACH HOTEL

SELECT PROPERTY_NAME , AVG(RATINGS_GIVEN) AS RATINGS
FROM DIM_HOTELS INNER JOIN FACT_BOOKINGS
ON DIM_HOTELS.PROPERTY_ID = FACT_BOOKINGS.PROPERTY_ID
GROUP BY 1 
ORDER BY 2;

#26. WEEK WISE REVENUE , BOOKING COUNT

SELECT `WEEK NO` , COUNT(BOOKING_ID) AS "BOOKING COUNT" , SUM(REVENUE_REALIZED) AS REVENUE
FROM DIM_DATE INNER JOIN FACT_BOOKINGS
ON DIM_DATE.DATE = FACT_BOOKINGS.BOOKING_DATE
GROUP BY 1 
ORDER BY 2 ASC;

#26. WEEK WISE OCCUPANCY , BOOKING COUNT

SELECT `WEEK NO` , SUM(SUCCESSFUL_BOOKINGS) AS "BOOKING COUNT" , ((SUM(SUCCESSFUL_BOOKINGS)/SUM(CAPACITY))*100) AS OCCUPANCY
FROM DIM_DATE INNER JOIN FACT_AGGREGATED_BOOKINGS
ON DIM_DATE.DATE = FACT_AGGREGATED_BOOKINGS.CHECK_IN_DATE
GROUP BY 1
ORDER BY 2 DESC;

#27. METRICS : REVENUE

SELECT SUM(REVENUE_REALIZED) AS REVENUE FROM FACT_BOOKINGS;

#27. METRICS : BOOKING COUNT

SELECT COUNT(BOOKING_ID) AS "BOOKING COUNT" FROM FACT_BOOKINGS;

##27. METRICS : CAPACITY

SELECT SUM(CAPACITY) AS "TOTAL CAPACITY" FROM FACT_AGGREGATED_BOOKINGS;

#27. METRICS : TOTAL SUCCESSFUL BOOKINGS

SELECT SUM(SUCCESSFUL_BOOKINGS) AS "TOTAL SUCCESSFUL BOOKINGS" FROM FACT_AGGREGATED_BOOKINGS;

#27. METRICS : NO OF DAYS

SELECT ABS((DATEDIFF(MIN(`DATE`),MAX(`DATE`))+1)) AS "NO OF DAYS" FROM DIM_DATE;

#28. BOOKING % BY PLATFORM

SELECT BOOKING_PLATFORM , COUNT(BOOKING_ID) , COUNT(BOOKING_ID)*100/SUM(COUNT(BOOKING_ID)) OVER() AS "BOOKING %"
FROM FACT_BOOKINGS 
GROUP BY 1
ORDER BY 2 ;

#29. BOOKING % BY CLASS

SELECT ROOM_CLASS ,COUNT(BOOKING_ID) AS "BOOKING COUNT", (COUNT(BOOKING_ID)*100/SUM(COUNT(BOOKING_ID)) OVER()) AS  "BOOKING %"
FROM DIM_ROOMS INNER JOIN FACT_BOOKINGS
ON DIM_ROOMS.ROOM_ID = FACT_BOOKINGS.ROOM_CATEGORY
GROUP BY 1 
ORDER BY 2;

#30. BOOKING % BY HOTEL

SELECT PROPERTY_NAME ,COUNT(BOOKING_ID) AS "BOOKING COUNT", (COUNT(BOOKING_ID)*100/SUM(COUNT(BOOKING_ID)) OVER()) AS  "BOOKING %"
FROM DIM_HOTELS INNER JOIN FACT_BOOKINGS
ON DIM_HOTELS.PROPERTY_ID = FACT_BOOKINGS.PROPERTY_ID
GROUP BY 1 
ORDER BY 2;

#31. BOOKING % BY DAYTYPE

SELECT DAY_TYPE ,COUNT(BOOKING_ID) AS "BOOKING COUNT", (COUNT(BOOKING_ID)*100/SUM(COUNT(BOOKING_ID)) OVER()) AS  "BOOKING %"
FROM DIM_DATE INNER JOIN FACT_BOOKINGS
ON DIM_DATE.`DATE` = FACT_BOOKINGS.BOOKING_DATE
GROUP BY 1 
ORDER BY 2;

#32. AVERAGE DAILY RATE ADR

SELECT (SUM(REVENUE_REALIZED)/COUNT(BOOKING_ID)) AS "AVERAGE DAILY RATE" FROM FACT_BOOKINGS;

#33. BOOKING STATUS % 

SELECT BOOKING_STATUS ,COUNT(BOOKING_ID) AS " COUNT", (COUNT(BOOKING_ID)*100/SUM(COUNT(BOOKING_ID)) OVER()) AS  "COUNT %"
FROM  FACT_BOOKINGS
GROUP BY 1 
ORDER BY 2;

#34. REALISATION %

SELECT ABS(1-((SUM(IF(BOOKING_STATUS='CANCELLED',1,0)))*100/COUNT(BOOKING_ID)+(SUM(IF(BOOKING_STATUS='NO SHOW',1,0)))*100/COUNT(BOOKING_ID))) AS "REALISATION%" 
FROM FACT_BOOKINGS;

#35. REVENUE PER AVAILABLE ROOM

SELECT 
    SUM(b.revenue_generated) / SUM(a.capacity) AS "REVENUE PER AVAILABLE ROOM"
FROM
    (SELECT room_category, SUM(revenue_generated) AS revenue_generated
     FROM fact_bookings
     GROUP BY room_category) b
JOIN
    (SELECT room_category, SUM(capacity) AS capacity
     FROM fact_aggregated_bookings
     GROUP BY room_category) a
ON b.room_category = a.room_category;


SELECT * FROM FACT_AGGREGATED_BOOKINGS;

#36. DAILY BOOKED ROOM NIGHT

SELECT COUNT(BOOKING_ID)/ABS((DATEDIFF(MIN(`DATE`),MAX(`DATE`))+1)) AS "DAILY BOOKED ROOM NIGHT"
FROM DIM_DATE INNER JOIN FACT_BOOKINGS
ON DIM_DATE.`DATE`=FACT_BOOKINGS.BOOKING_DATE;

#37. DAILY SELLABLE ROOM NIGHT

SELECT SUM(CAPACITY)/ABS((DATEDIFF(MIN(`DATE`),MAX(`DATE`))+1)) AS "DAILY SELLABLE ROOM NIGHT"
FROM DIM_DATE INNER JOIN FACT_AGGREGATED_BOOKINGS
ON DIM_DATE.`DATE`=FACT_AGGREGATED_BOOKINGS.CHECK_IN_DATE;

#38. DAILY UTILLIZED ROOM NIGHT

SELECT SUM(IF(BOOKING_STATUS='CHECKED OUT',1,0))/ABS((DATEDIFF(MIN(`DATE`),MAX(`DATE`))+1)) AS "DAILY UTILLIZED ROOM NIGHT"
FROM DIM_DATE INNER JOIN FACT_BOOKINGS
ON DIM_DATE.`DATE` = FACT_BOOKINGS.BOOKING_DATE;
